// GENERATED by scripts/prepare-arrival-images.mjs — do not edit by hand.

export type ImageRole =
  | "converge-field" | "orbit" | "arrival-card" | "flank-cube"
  | "breather" | "invitation-bg" | "island-card";

export interface ArrivalImage {
  /** Path of the largest generated tier under public/. */
  src: string;
  width: number;
  height: number;
  /** Available width tiers; swap the trailing -<w>.webp to pick one. */
  tiers: number[];
  alt: string;
  role: ImageRole;
}

export const arrivalImages = {
  "act-1-converge": [
    {
      "src": "/images/act-1-converge/coast-aerial-1920.webp",
      "width": 1160,
      "height": 1160,
      "tiers": [
        1920,
        640
      ],
      "alt": "Aerial view of a white-sand coastline meeting turquoise ocean",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/lobby-light-hall-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Grand stone lobby hall washed in angled daylight",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/arva-sunset-bonsai-1920.webp",
      "width": 936,
      "height": 1232,
      "tiers": [
        1920,
        640
      ],
      "alt": "Restaurant window at sunset with a silhouetted bonsai",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/premier-room-dusk-1920.webp",
      "width": 1160,
      "height": 1160,
      "tiers": [
        1920,
        640
      ],
      "alt": "Hotel room at dusk overlooking the city skyline",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/spa-pool-lightshafts-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Indoor stone pool crossed by shafts of sunlight",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/cafe-forest-exterior-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Glass cafe pavilion nested in a green forest",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/indoor-pool-blue-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Indoor pool with cool blue glass wall",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/round-window-ikebana-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Round window alcove with an ikebana arrangement",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/dark-pool-dusk-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Dark stone pool at dusk with city lights beyond",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/calligraphy-hand-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Hand drawing ink calligraphy on washi paper",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/kyoto-suite-living-1920.webp",
      "width": 1160,
      "height": 1160,
      "tiers": [
        1920,
        640
      ],
      "alt": "Bright suite living room facing a forest garden",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/spring-cafe-forest-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Cafe terrace among fresh spring foliage",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/suite-bath-city-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Deep stone bath beside a window over the city",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/amanemu-lake-aerial-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Aerial view of forested islands in a still lake at dusk",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/mori-suite-table-1920.webp",
      "width": 1920,
      "height": 1920,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Warm timber suite with round dining table",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/mori-suite-lantern-1920.webp",
      "width": 1080,
      "height": 668,
      "tiers": [
        1920,
        640
      ],
      "alt": "Timber suite interior under a woven lantern",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/resort-walkway-1920.webp",
      "width": 1920,
      "height": 1920,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Guest walking along a minimal resort walkway at golden hour",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/resort-rooftops-1920.webp",
      "width": 1920,
      "height": 1184,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Resort pavilions with dark rooftops in green hills",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/sunset-hills-1920.webp",
      "width": 1086,
      "height": 1086,
      "tiers": [
        1920,
        640
      ],
      "alt": "Hilltop pavilion silhouetted against a sunset sky",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/spa-treatment-room-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Serene spa treatment room in pale timber",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/spa-hall-arch-1920.webp",
      "width": 1920,
      "height": 1920,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Arched spa hall with soft symmetric lighting",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/steam-bath-window-1920.webp",
      "width": 1920,
      "height": 1920,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Steaming outdoor bath framing sky and trees",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/pearl-diver-1920.webp",
      "width": 1520,
      "height": 2000,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Pearl diver surfacing in open blue water",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/temple-gate-1920.webp",
      "width": 1520,
      "height": 2000,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Stone temple gate at the end of a white path",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/forest-procession-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Priests walking a forest path in white robes",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/red-bridge-garden-1920.webp",
      "width": 1920,
      "height": 1920,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Vermilion bridge arching through a temple garden",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/forest-steps-kimono-1920.webp",
      "width": 1459,
      "height": 1920,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Figures in kimono climbing mossy forest steps",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/library-lounge-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Warm library lounge with vaulted ceiling",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/timber-bedroom-1920.webp",
      "width": 1520,
      "height": 2000,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Bedroom under a high timber vault",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/pool-pavilion-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Open-air pavilion reflected in a still pool",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/lounge-columns-dusk-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Soaring lattice columns in a dusk-lit lounge",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/coast-dusk-aerial-1920.webp",
      "width": 1086,
      "height": 1430,
      "tiers": [
        1920,
        640
      ],
      "alt": "Aerial coastline with resort rooftops at dusk",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/patisserie-bread-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Fresh breads and pastries on grey stone",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/bonsai-hands-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Hands trimming a bonsai pine with brass scissors",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/sushi-counter-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Chef preparing at a pale timber sushi counter",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/room-park-view-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Suite window seat overlooking a green park and skyline",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/suite-lounge-sky-1920.webp",
      "width": 936,
      "height": 936,
      "tiers": [
        1920,
        640
      ],
      "alt": "Suite lounge corner with a tower view",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/terrace-lunch-sea-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Terrace dining room open to a sea view",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/waterfall-cliff-1920.webp",
      "width": 1086,
      "height": 1086,
      "tiers": [
        1920,
        640
      ],
      "alt": "Waterfall dropping down a forested cliff",
      "role": "converge-field"
    },
    {
      "src": "/images/act-1-converge/dark-pool-silhouette-1920.webp",
      "width": 936,
      "height": 936,
      "tiers": [
        1920,
        640
      ],
      "alt": "Figure walking beside a dark reflecting pool at dawn",
      "role": "converge-field"
    }
  ],
  "act-2-orbit": [
    {
      "src": "/images/act-2-orbit/round-window-detail-1920.webp",
      "width": 936,
      "height": 1232,
      "tiers": [
        1920,
        640
      ],
      "alt": "Round window with ikebana, portrait crop",
      "role": "orbit"
    },
    {
      "src": "/images/act-2-orbit/kaiseki-bento-1920.webp",
      "width": 1086,
      "height": 1086,
      "tiers": [
        1920,
        640
      ],
      "alt": "Kaiseki breakfast set in lacquer boxes",
      "role": "orbit"
    },
    {
      "src": "/images/act-2-orbit/tea-terrace-sunset-1920.webp",
      "width": 1920,
      "height": 1920,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Tea set on a terrace table at sunset",
      "role": "orbit"
    },
    {
      "src": "/images/act-2-orbit/water-ladle-1920.webp",
      "width": 1520,
      "height": 2000,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Water poured over hands from a bamboo ladle",
      "role": "orbit"
    },
    {
      "src": "/images/act-2-orbit/shell-delicacy-1920.webp",
      "width": 1520,
      "height": 2000,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Grilled shellfish served on a wooden tray",
      "role": "orbit"
    },
    {
      "src": "/images/act-2-orbit/spring-leaves-glass-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Champagne glasses against fresh maple leaves",
      "role": "orbit"
    },
    {
      "src": "/images/act-2-orbit/forest-champagne-1920.webp",
      "width": 936,
      "height": 1232,
      "tiers": [
        1920,
        640
      ],
      "alt": "Champagne bucket on a table amid green forest",
      "role": "orbit"
    },
    {
      "src": "/images/act-2-orbit/bread-detail-1920.webp",
      "width": 936,
      "height": 1232,
      "tiers": [
        1920,
        640
      ],
      "alt": "Artisan breads on stone, portrait crop",
      "role": "orbit"
    },
    {
      "src": "/images/act-2-orbit/bonsai-hands-detail-1920.webp",
      "width": 936,
      "height": 936,
      "tiers": [
        1920,
        640
      ],
      "alt": "Bonsai trimming close-up, portrait crop",
      "role": "orbit"
    },
    {
      "src": "/images/act-2-orbit/patisserie-piping-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Pastry chef piping matcha cream",
      "role": "orbit"
    },
    {
      "src": "/images/act-2-orbit/skincare-bottles-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Dark skincare vessels against grey stone",
      "role": "orbit"
    },
    {
      "src": "/images/act-2-orbit/massage-stones-1920.webp",
      "width": 1086,
      "height": 1430,
      "tiers": [
        1920,
        640
      ],
      "alt": "Warm stones placed along a guest back",
      "role": "orbit"
    }
  ],
  "act-4-room": [
    {
      "src": "/images/act-4-room/arrival-card-lobby-1920.webp",
      "width": 936,
      "height": 1232,
      "tiers": [
        1920,
        640
      ],
      "alt": "Grand lobby hall in warm light, portrait",
      "role": "arrival-card"
    },
    {
      "src": "/images/act-4-room/stone-counter-flowers-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Raw stone counter beneath hanging flowers",
      "role": "flank-cube"
    },
    {
      "src": "/images/act-4-room/arrival-card-alt-pool-1920.webp",
      "width": 936,
      "height": 1232,
      "tiers": [
        1920,
        640
      ],
      "alt": "Stone pool with light shafts, portrait",
      "role": "arrival-card"
    },
    {
      "src": "/images/act-4-room/chef-grill-fire-1920.webp",
      "width": 1520,
      "height": 2000,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Chef grilling skewers over open flame",
      "role": "flank-cube"
    },
    {
      "src": "/images/act-4-room/armchair-corner-1920.webp",
      "width": 1520,
      "height": 2000,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Cream armchairs beneath a botanical artwork",
      "role": "flank-cube"
    },
    {
      "src": "/images/act-4-room/arva-dark-tables-1920.webp",
      "width": 936,
      "height": 936,
      "tiers": [
        1920,
        640
      ],
      "alt": "Dark dining room with set tables, portrait",
      "role": "flank-cube"
    },
    {
      "src": "/images/act-4-room/spa-shelf-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Spa apothecary shelf over a carved wood basin",
      "role": "flank-cube"
    },
    {
      "src": "/images/act-4-room/piping-detail-1920.webp",
      "width": 936,
      "height": 1404,
      "tiers": [
        1920,
        640
      ],
      "alt": "Matcha dessert piping close-up, portrait",
      "role": "flank-cube"
    },
    {
      "src": "/images/act-4-room/skincare-vases-1920.webp",
      "width": 936,
      "height": 1232,
      "tiers": [
        1920,
        640
      ],
      "alt": "Skincare vessels in soft daylight, portrait",
      "role": "flank-cube"
    },
    {
      "src": "/images/act-4-room/suite-lounge-day-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Suite lounge with low daybed and city light",
      "role": "flank-cube"
    },
    {
      "src": "/images/act-4-room/pool-colonnade-1920.webp",
      "width": 936,
      "height": 1232,
      "tiers": [
        1920,
        640
      ],
      "alt": "Teal pool along a sunlit stone colonnade, portrait",
      "role": "flank-cube"
    },
    {
      "src": "/images/act-4-room/colonnade-detail-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Sunlit stone colonnade detail",
      "role": "flank-cube"
    }
  ],
  "act-5-breathe": [
    {
      "src": "/images/act-5-breathe/breathe-dining-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Restaurant wrapped in fresh forest green",
      "role": "breather"
    },
    {
      "src": "/images/act-5-breathe/breathe-spa-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Glass-walled pool above the city skyline",
      "role": "breather"
    },
    {
      "src": "/images/act-5-breathe/breathe-rooms-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Suite bedroom facing the morning skyline",
      "role": "breather"
    }
  ],
  "act-6-invite": [
    {
      "src": "/images/act-6-invite/onsen-steam-dusk-1920.webp",
      "width": 1086,
      "height": 1086,
      "tiers": [
        1920,
        640
      ],
      "alt": "Bather in a steaming onsen at dusk",
      "role": "invitation-bg"
    },
    {
      "src": "/images/act-6-invite/welcome-pavilion-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Welcome pavilion glowing at dusk",
      "role": "invitation-bg"
    }
  ],
  "nav-island": [
    {
      "src": "/images/nav-island/island-stay-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Warm timber suite bedroom, landscape",
      "role": "island-card"
    },
    {
      "src": "/images/nav-island/island-restore-1920.webp",
      "width": 1913,
      "height": 1912,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Wellness session in a bright forest-view studio",
      "role": "island-card"
    },
    {
      "src": "/images/nav-island/island-dine-1920.webp",
      "width": 1920,
      "height": 1186,
      "tiers": [
        1920,
        1280,
        640
      ],
      "alt": "Vaulted dining hall with curved timber ceiling",
      "role": "island-card"
    }
  ]
} as const satisfies Record<string, readonly ArrivalImage[]>;

export type ActKey = keyof typeof arrivalImages;
